# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.23.1"

      - name: Generate
        run: go run -v ./...
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_ID_CHAN: ${{ secrets.TELEGRAM_ID_CHAN }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: "_site/"

      # Deploy Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
