# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: "1.23.1"

      - name: Generate
        run: go run -v ./...

      - name: Upload pages artifact
        uses: actions/upload-artifact@v4

      # Deploy Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
